name = "DataValues"
uuid = "e7dc6d0d-1eca-5fa6-8ad6-5aecde8b7ea5"
version = "0.4.13-DEV"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DataValueInterfaces = "e2d170a0-9d28-54be-80f0-106bbe20a464"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "InteractiveUtils", "LinearAlgebra", "Random"]

[compat]
julia = "1"
